<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robo_car">

    <!-- <xacro:arg name="laser_visual" default="false"/> -->

    <!-- LIDAR LINK FRAME -->

    <joint name="lidar_joint" type="fixed">
        <parent link="base_chassis_link"/>
        <child link="lidar_link"/>
        <origin xyz="-0.05 0 ${full_chassis_height + 0.04}" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>

    <link name="lidar_link">
    <visual>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05" />
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05" />
      </geometry>
    </collision>
    
    <xacro:inertial_cylinder mass="0.2" length="0.05" radius="0.05">
            <origin xyz="0 0 -0.02" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>





    <gazebo reference="lidar_link">
        <material>Gazebo/DarkGrey</material>
        <sensor name="lidar" type="ray">
            <always_on>true</always_on>
            <visualize>$(arg laser_visual)</visualize>
            <pose>0.0 0 0.0 0 0 0</pose>
            <update_rate>15</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>${0*pi}</min_angle>
                    <max_angle>${2*pi}</max_angle>
                </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>5</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="laser_plugin" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <namespace>lidar</namespace>
                <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>  
    </gazebo>


  
</robot>