<?xml version="1.0"?>
<robot name="robo_car" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="material_black">
        <material name="black">
            <color rgba="0.1 0.1 0.1 1"/>
        </material>
    </xacro:macro>

    <xacro:macro name="material_blue">
        <material name="blue">
            <color rgba="0.2 0.2 1 1"/>
        </material>
    </xacro:macro>

    <xacro:macro name="material_red">
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
    </xacro:macro>


    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>


     <!-- GAZEBO WHEEL PARAMETERS -->
    <xacro:macro name="gazebo_wheel_settings" params="name">
        <gazebo reference="${name}">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <kp>5000000</kp>
            <kd>0.1</kd>
            <!-- <fdir1>1 0 0</fdir1> -->
            <minDepth>0.002</minDepth>
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="gazebo_rim_settings" params="name">
        <gazebo reference="${name}">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>
    <!--  ########################### -->




    <xacro:macro name="insert_drive_wheel" params="base_name parent_name x y z mass radius thickness spoke_width">
        <joint name="${base_name}_joint" type="continuous">
            <parent link="${parent_name}"/>
            <child link="${base_name}"/>
            <origin xyz="${x} ${y} ${z}" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>

        <link name="${base_name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                </geometry>
                <xacro:material_black/>
            </visual>
            <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${thickness}"/>
                    <!-- <sphere radius="${radius}"/> -->
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${mass}" length="${thickness}" radius="${radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <xacro:gazebo_wheel_settings name="${base_name}"/>

        <joint name="${base_name}_rim_joint" type="fixed">
            <parent link="${base_name}"/>
            <child link="${base_name}_rim"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <link name="${base_name}_rim">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.2} ${thickness+0.005}"/>
                </geometry>
                <xacro:material_red/>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.2} ${thickness+0.005}"/>
                </geometry>
                <xacro:material_red/>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-pi/4}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.2} ${thickness+0.005}"/>
                </geometry>
                <xacro:material_red/>
            </visual>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${pi/4}"/>
                <geometry>
                    <box size="${spoke_width} ${radius*1.2} ${thickness+0.005}"/>
                </geometry>
                <xacro:material_red/>
            </visual>

        </link>

        <xacro:gazebo_rim_settings name="${base_name}_rim"/>

    </xacro:macro>

    
</robot>